context_entity_selection_order: highest_prob
data_dir: ./data/entity_disambiguation
do_eval: true
do_test: true
do_train: false
document_split_mode: per_mention
local_rank: -1
masked_entity_prob: 0.9
master_port: 29500
max_candidate_length: 30
max_seq_length: 512
model_file: ./data/luke_large_ed
no_context_entities: false
num_gpus: 1
num_train_epochs: 2
output_dir: ./output/results/exp_2021-12-07 11:43:35
seed: 1
test_set:
- ace2004
- aquaint
train_batch_size: 1
update_entity_bias: false
update_entity_emb: false
